Taproot receive
digitalbitbox/bitbox-wallet-app pull request #1639
Opened 2022-02-16 14:22 UTC by benma

2022-02-16 14:30 UTC, benma commented
@thisconnect you will need a BitBox02 v9.10.0 to see taproot accounts. In this PR, taproot is only added to *new* accounts, so either delete accounts.json before, or add a new account to see it.

The receive screen now shows all the available address type options. Please fix up the styling :smile: The new locize keys have no text yet, we can discuss what to put there.

2022-02-17 09:51 UTC, thisconnect requested changes
made a comment to fix eth

2022-02-17 10:06 UTC, benma commented on frontends/web/src/routes/account/receive/receive.tsx
> +    private availableScriptTypes: accountApi.ScriptType[] = scriptTypes.filter(sc => this.props.receiveAddresses.findIndex(addrs => addrs.scriptType !== null ? sc === addrs.scriptType : -1) >= 0);
good catch! done

2022-02-19 08:18 UTC, thisconnect approved these changes
Got taproot addresses with v9.10.0 and deleted accounts.json 👍 

also tested current address types with current firmware and btc ltc eth 👍 

one weird case was when I tested same wallet with a different device that has the old firmware the Bitcoin accounts that received taproot didn't show. Adding did not let me add the first account.

other than that LGTM 👍

2022-02-20 11:38 UTC, benma commented
> one weird case was when I tested same wallet with a different device that has the old firmware the Bitcoin accounts that received taproot didn't show. Adding did not let me add the first account.

Great testing, thanks! The account is missing due to this check:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/2df942ab1955dbac02b0e6bf9b9bae0fdbbc955d/backend/accounts.go#L643-L645

Not sure what to do about it, if anything.

2022-02-20 12:19 UTC, benma commented
@thisconnect your PR and my fixup didn't consider the order of the addresses in

```
const scriptTypes: accountApi.ScriptType[] = ['p2wpkh', 'p2tr', 'p2wpkh-p2sh']
```

I fixed it now to cycle through the types in that order.

2022-02-20 12:51 UTC, merged