frontend: update cointracking link
digitalbitbox/bitbox-wallet-app pull request #1705
Opened 2022-05-24 10:08 UTC by jstrnbrg

Cointracking asked us to append a unique ref to their link.

2022-05-24 10:12 UTC, benma requested changes
please change commit msg from `backend:` to `frontend:` too

2022-05-24 10:12 UTC, benma commented on backend/backend.go
> +	"https://cointracking.info/import/bitbox/?aa=511",
i don't think this is needed here, the whitelist is a prefix-check only

2022-05-25 11:43 UTC, jstrnbrg commented
All good? @benma

2022-05-25 11:53 UTC, benma commented
@jstrnbrg did you run this change and click the link? did it work?

2022-05-25 11:57 UTC, jstrnbrg commented
> @jstrnbrg did you run this change and click the link? did it work?

yes I did test it locally :)
<img width="1440" alt="Screenshot 2022-05-25 at 12 57 14" src="https://user-images.githubusercontent.com/34884458/170256652-ee2f1eef-2cd3-4179-96a0-e14a1a0b6586.png">

2022-05-25 12:10 UTC, benma commented
@jstrnbrg including clicking it? :D

2022-05-25 12:12 UTC, jstrnbrg commented
> @jstrnbrg including clicking it? :D

yes lol 
<img width="1440" alt="Screenshot 2022-05-25 at 13 11 43" src="https://user-images.githubusercontent.com/34884458/170259024-091bba72-6a7d-49d3-830b-b9fce8e6969b.png">

2022-05-25 13:20 UTC, benma approved these changes
utACK

2022-05-25 13:21 UTC, merged