frontend: make locize-pull
digitalbitbox/bitbox-wallet-app pull request #1717
Opened 2022-06-20 09:12 UTC by benma

2022-06-20 10:19 UTC, thisconnect requested changes

2022-06-20 11:56 UTC, benma commented on frontends/web/src/locales/pt/app.json
> +    "openFile": "",
idk, @jstrnbrg ?

2022-06-20 11:58 UTC, benma commented on frontends/web/src/locales/pt/app.json
> +    "synchronizing": "",
It was removed in cea8aeb6257fe4402320a2e6533ae921fc0cf1db. I am not sure why locize doesn't delete the keys in the other languages. Need to check, but not a blocker here.

2022-06-20 11:58 UTC, benma commented on frontends/web/src/locales/pt/app.json
> +    "openFile": "",
Same as https://github.com/digitalbitbox/bitbox-wallet-app/pull/1717#discussion_r901583316, the key was deleted in `en`.

2022-08-30 12:02 UTC, benma commented
Rebased and pulled again

2022-09-01 11:58 UTC, thisconnect requested changes
Find some inconsistencies and opened a few PRs

Also in the is a wrong sentence in the passphrase-disable-success-message

2022-09-01 11:58 UTC, thisconnect commented on frontends/web/src/locales/de/app.json
> +      "message": "Optionale Passphrase <strong>erfolgreich deaktiviert</strong>!\nVon nun an wirst du aufgefordert, eine Passphrase anzugeben.",
This is wrong, when it is successfully deactivated it should say "Von nun an wirst du nicht mehr aufgefordert eine Passphrase anzugeben." or similar.

2022-09-01 11:58 UTC, thisconnect commented on frontends/web/src/locales/de/app.json
> +    "changeScriptType": "Addresstyp ändern",
Adresstyp

2022-09-01 11:59 UTC, thisconnect commented on frontends/web/src/locales/de/app.json
> +      "message": "Optionale Passphrase <strong>erfolgreich deaktiviert</strong>!\nVon nun an wirst du aufgefordert, eine Passphrase anzugeben.",
cc @jstrnbrg

2022-09-10 19:58 UTC, benma commented on frontends/web/src/locales/de/app.json
> +      "p2wpkh-p2sh": "Älteren Segwit erweiterten öffentlichen Schlüssel anzeigen"
@thisconnect feel free to decide and fix on locize, I don't mind either way :)

2022-09-10 19:58 UTC, benma commented
Pulled and rebased again

2022-09-13 13:34 UTC, thisconnect commented on frontends/web/src/locales/it/app.json
> +        "text": "",
Translated with help from SpaghettiMonster, @benma could you pull again?

2022-09-13 13:36 UTC, thisconnect commented on frontends/web/src/locales/it/app.json
> +        "text": "",
this one would be nice other than that LGTM

2022-09-29 10:48 UTC, benma commented on frontends/web/src/locales/de/app.json
> +    "subtotalWithCoinName": "({{coinName}}) - Summe",
I agree with @thisconnect and I fixed it on locize.

2022-09-29 10:51 UTC, benma commented on frontends/web/src/locales/de/app.json
> +    "success": "Erfolg"
The whole `generic` section seems unused. git blame shows it was used for the BitBoxBase: 

![image](https://user-images.githubusercontent.com/1225267/193012436-f4a82d0d-ef58-48ef-82b2-964a9969182f.png)

I added a commit to remove it.

2022-09-29 10:51 UTC, benma commented
Rebased again :smile:

2022-09-29 11:07 UTC, thisconnect commented on frontends/web/src/locales/de/app.json
> +      "p2wpkh-p2sh": "Älteren Segwit erweiterten öffentlichen Schlüssel anzeigen"
soon™

2022-09-29 11:09 UTC, thisconnect commented on frontends/web/src/locales/de/app.json
> +    "success": "Erfolg"
I see `generic.confirmToContinue` and `generic.enabled` is used, all others can be removed

2022-10-03 07:34 UTC, benma commented on frontends/web/src/locales/de/app.json
> +    "success": "Erfolg"
Restored generic.enabled!

2022-10-03 08:05 UTC, thisconnect approved these changes
LGTM

2022-10-03 08:09 UTC, merged