Allow setting a Custom Bitcoin block explorer (Issue 1774)
digitalbitbox/bitbox-wallet-app pull request #1783
Opened 2022-09-29 14:51 UTC by mdcmeridius

https://github.com/digitalbitbox/bitbox-wallet-app/issues/1774

Bitbox app settings (note: outdated screenshots, will be "Custom **Bitcoin** block explorer"):
![image](https://user-images.githubusercontent.com/114249714/193064291-56ec9db9-665b-41cc-8034-89ebd09f94a5.png)
![image](https://user-images.githubusercontent.com/114249714/193064347-f6011f5b-b053-42a1-8810-abbe61413dcc.png)

Before clicking on transaction link:
![image](https://user-images.githubusercontent.com/114249714/193064388-3394a371-abd5-4109-bb7e-7b457d07393b.png)

After clicking on transaction link:
![image](https://user-images.githubusercontent.com/114249714/193064422-cd456854-b445-48de-857e-a940d6f9a9ce.png)

2022-09-29 14:52 UTC, mdcmeridius commented
NOTE: this PR also includes changes to compile_windows.bat, so it becomes more flexible and works with other Visual Studio flavors (Professional, Enterprise, etc.).

2022-09-29 18:07 UTC, thisconnect commented
looks very nice 👍 

please open a separate PR for the VS support.

https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/CONTRIBUTING.md

2022-10-03 07:37 UTC, benma requested changes

2022-10-03 07:37 UTC, benma commented on backend/config/config.go
> +	BTCBlockExplorer blockExplorerConfig `json:"blockExplorer"`
please move this to `btcCoinConfig`, which allows extending this feature to testnet and alts in the future.

2022-10-03 07:37 UTC, benma commented on frontends/qt/compile_windows.bat
> +setlocal
Please remove the build commits from this PR, as you moved it to #1784

2022-10-03 07:37 UTC, benma commented on frontends/web/src/routes/settings/settings.tsx
> +      restart: false,
remove this? if the restart flag is set it means a restart is needed. Changing the block explorer form does not change that.

2022-10-04 14:35 UTC, mdcmeridius commented on backend/config/config.go
> +	URL     string `json:"blockExplorerURL"`
I agree.

2022-10-09 10:17 UTC, mdcmeridius commented
I'm giving this PR because the maintainers of this project are too picky and not very smart.
If you want a sucky product, suit yourselves!
GOODBYE

2022-10-09 10:20 UTC, closed without merging