frontend: changed return types & children types for FC
digitalbitbox/bitbox-wallet-app pull request #1839
Opened 2022-11-14 06:17 UTC by shonsirsha

As a part of our refactoring effort in the FE to increase our code's readability and consistency as well as following the best practices and conventions, we'd like to change several things mentioned below for our functional components (FC):

1. If a component optionally accepts children we keep using `FunctionComponent` as we do already (or start to use one when it isn't used yet).

2. If a component does not accept any children we remove `FunctionComponent` and `PropsWithChildren`.

3. Remove return type `JSX.Element` or `JSX.Element | null.`

4. Children's type is mostly `ReactNode`. When component must only have exactly 1 child, the type is `ReactChild`.

Also changed Interface to Type whenever possible.

2022-11-14 08:15 UTC, thisconnect requested changes

2022-11-14 08:15 UTC, thisconnect commented on frontends/web/src/components/sidebar/sidebar.tsx
> +type TGetAccountLinkProps = IAccount & { handleSidebarItemClick: ((e: React.SyntheticEvent) => any) };
since you are here anyway, please return `void` instead of `any`

2022-11-14 08:15 UTC, thisconnect commented on frontends/web/src/routes/account/add/components/steps.tsx
> +
nit: remove newline? 😇

2022-11-14 08:15 UTC, thisconnect commented on frontends/web/src/routes/device/bitbox02/components/password-entry/password-entry.tsx
> +export const PasswordEntry: FunctionComponent = ({ children }) => {
`<PasswordEntry />` never uses children props remove `FunctionComponent` and `children`.

2022-11-15 01:01 UTC, shonsirsha commented
Oops, forgot to comment. Changes have been made, PTAL 🙏 @thisconnect

2022-11-15 08:50 UTC, thisconnect approved these changes
checked https://github.com/digitalbitbox/bitbox-wallet-app/compare/bc791a70ac12132cfe98fadcb791bcf37f68a880..1424572aaa63a0a0a4e524b48db2ecd1baf3c392

nice 👍  LGTM

2022-11-15 09:33 UTC, merged