ci/scripts: trevis cleanup
digitalbitbox/bitbox-wallet-app pull request #1974
Opened 2023-02-23 09:38 UTC by Beerosagos

Travis is not used anymore: this deletes unused related files and refactor scripts to remove travis refs.

2023-02-27 08:38 UTC, benma requested changes
Typo in commit: trevis -> travis

2023-02-27 08:38 UTC, benma commented on .github/workflows/ci.yml
> +          GITHUB_OS_NAME: linux
TRAVIS_OS_NAME is a real env var in travis. GITHUB_OS_NAME is not a real env var in GH CI. Maybe best to rename it to simply OS_NAME or CI_OS_NAME.

2023-02-27 15:48 UTC, Beerosagos commented
Updated, thanks! PTAL

2023-03-03 15:30 UTC, benma reviewed
LGTM

2023-03-06 08:19 UTC, merged