frontend: convert signingconfiguration to functional component
digitalbitbox/bitbox-wallet-app pull request #2010
Opened 2023-03-13 07:54 UTC by shonsirsha

To follow the latest conventions and best practices of React, we'd like to convert our class components into functional ones.

Here, we're converting `signingconfiguration.tsx` into a functional component.

2023-03-13 10:49 UTC, thisconnect requested changes

2023-03-13 10:49 UTC, thisconnect commented on frontends/web/src/routes/account/info/signingconfiguration.tsx
> +    canVerifyExtendedPublicKeys();
could you try if would it work to use useLoad like this `const canVerifyExtendedPublicKeys = useLoad(getCanVerifyXPub(code))` instead, this needs a change in getCanVerifyXPub in `api/accounts` like https://github.com/digitalbitbox/bitbox-wallet-app/blob/cff4fd84d8cc219ebb2ebd7bc64d688fe7e4c7c2/frontends/web/src/api/account.ts#L109-L113

2023-03-13 11:33 UTC, shonsirsha commented on frontends/web/src/routes/account/info/signingconfiguration.tsx
> +import { useTranslation } from 'react-i18next';
I agree! :)

2023-03-14 04:30 UTC, shonsirsha commented on frontends/web/src/routes/account/info/signingconfiguration.tsx
> +    canVerifyExtendedPublicKeys();
good idea!

2023-03-14 04:31 UTC, shonsirsha commented
PTAL @thisconnect :)

2023-03-14 07:45 UTC, thisconnect approved these changes
LGTM with nit

2023-03-14 07:45 UTC, thisconnect commented on frontends/web/src/routes/account/info/signingconfiguration.tsx
>    };
nit: looks like it could be directly called in the onClick handler without having a function here.

2023-03-14 08:18 UTC, merged