backend/handlers: use handlers that can't return an error
digitalbitbox/bitbox-wallet-app pull request #2087
Opened 2023-04-28 21:34 UTC by benma

The error returned by handlers is not propagated to the frontend in production. For errors that should be displayed to the user, we currently use the `{ success: false }` pattern, sometimes with an error message and/or error code.

It has been a frequent confusion that one can simply return an error from the handler. This commit adds a non-error version of the handler function, with the goal that all handlers eventually use this one, so errors are properly handled in all cases.

2023-05-16 14:34 UTC, Beerosagos requested changes
I think there are a couple  small changes needed

2023-05-18 01:42 UTC, benma commented on backend/devices/bitbox02/handlers/handlers.go
> +		return map[string]interface{}{"success": true}
true! :stuck_out_tongue: fixed

2023-05-18 01:43 UTC, benma commented on frontends/web/src/components/qrcode/qrcode.tsx
> +  if (!qrCode) {
i don't think so - `qrCode` itself can be undefined. if it is defined, then either success=false or the data is available, both are handled below. the TS typechecker did well here!

2023-05-18 12:28 UTC, Beerosagos commented on frontends/web/src/components/qrcode/qrcode.tsx
> +  if (!qrCode) {
You're right! Don't know why I said that :D

2023-05-24 02:39 UTC, merged