docker: update ubuntu base image to 20.04
digitalbitbox/bitbox-wallet-app pull request #2110
Opened 2023-05-11 12:50 UTC by Beerosagos

We would like to update nodejs to v18.16.0, which requires libc6 with a higher version than that available on ubuntu 18.04 (which reached end of life on 30/04/2023). This commit updates shiftcrypto/qt5 and shiftcripto/bitbox-wallet-app docker images to be based upon ubuntu 20.04 and allows updating nodejs.

2023-05-18 02:23 UTC, benma requested changes
tACK. please:

- push the bitbox-wallet-app image to the github registry and update .github/workflows/ci.yml to point to `:19`
- tag `qt5:4` also as `qt5:latest` and push to dockerhub (https://hub.docker.com/r/shiftcrypto/qt5/tags)
- update docs/BUILD.md to specify 20.04+ instead of 18.04+
- add a CHANGELOG entry to state that 20.04+ is now the minimum supported Ubuntu

2023-05-22 12:15 UTC, Beerosagos commented
> tACK. please:
> 
>     * push the bitbox-wallet-app image to the github registry and update .github/workflows/ci.yml to point to `:19`

@benma This is done in #2100, ready for review

> 
>     * tag `qt5:4` also as `qt5:latest` and push to dockerhub (https://hub.docker.com/r/shiftcrypto/qt5/tags)
> 
>     * update docs/BUILD.md to specify 20.04+ instead of 18.04+
> 
>     * add a CHANGELOG entry to state that 20.04+ is now the minimum supported Ubuntu

Done, PTAL :pray:

2023-05-22 22:40 UTC, benma commented
> @benma This is done in #2100, ready for review

I'm confused now, as you already had pushed it to dockerhub https://hub.docker.com/layers/shiftcrypto/bitbox-wallet-app/19/images/sha256-86fe3425f81d47dd61d265e2bccc5995610949427ab12cd047d5ae13e38b643d?context=explore

Is the above image now including or not including the changes from #2100? 

Is the image in the GH registry the same?

2023-05-23 07:12 UTC, benma approved these changes

2023-05-23 07:16 UTC, merged

2023-05-23 07:20 UTC, Beerosagos commented
> > @benma This is done in #2100, ready for review
> 
> I'm confused now, as you already had pushed it to dockerhub https://hub.docker.com/layers/shiftcrypto/bitbox-wallet-app/19/images/sha256-86fe3425f81d47dd61d265e2bccc5995610949427ab12cd047d5ae13e38b643d?context=explore
> 
> Is the above image now including or not including the changes from #2100?
> 
> Is the image in the GH registry the same?
> 
> The image at GH (https://github.com/digitalbitbox/bitbox-wallet-app/pkgs/container/bitbox-wallet-app-ci/92458318?tag=19) says it was also uploaded 11 days ago as the one above on dockerhub, but the sha256sums don't match (`2031ffff2ebcd360d6f801dc2eac8f68d01ea494e7673ec489f99330377eae81` on GH vs `86fe3425f81d47dd61d265e2bccc5995610949427ab12cd047d5ae13e38b643d` on dockerhub).

Just writing here as a recap for the future: the docker image v19 already contains #2100 changes. Apparently, hashes of the same image from GH and docker are different, don't know exactly why.