frontend: created and used MessageWaitDialog for send screen
digitalbitbox/bitbox-wallet-app pull request #2199
Opened 2023-07-11 13:32 UTC by shonsirsha

Created and used MessageWaitDialog for send screen as a part of the `send.tsx` refactoring effort (#2190).

2023-07-11 13:33 UTC, shonsirsha commented on frontends/web/src/routes/account/send/send-guide.tsx
> -export default function SendGuide({ coinCode }: TProps) {
Using named export now. ✌️

2023-07-11 13:34 UTC, shonsirsha commented on frontends/web/src/routes/account/send/send-guide.tsx
> +export const SendGuide = ({ coinCode }: TProps) => {
Using named export now. ✌️

2023-07-11 14:00 UTC, thisconnect requested changes

2023-07-11 14:00 UTC, thisconnect commented on frontends/web/src/routes/account/send/components/dialogs/message-wait-dialog.tsx
> +  );
`switch(messageType)` would be nice

2023-07-12 08:21 UTC, shonsirsha commented on frontends/web/src/routes/account/send/components/dialogs/message-wait-dialog.tsx
> +const IconAndMessage = ({ messageType }: TIconProps) => {
Created a component that switches, PTAL @thisconnect  🙏

2023-07-12 08:46 UTC, thisconnect approved these changes
LGTM

2023-07-17 09:45 UTC, merged