frontend: created and used lazy loaded qrcode scanner hook
digitalbitbox/bitbox-wallet-app pull request #2224
Opened 2023-08-16 13:36 UTC by shonsirsha

to make lazy loaded qrcode scanner more reusable, we can create a hook for it

2023-08-16 13:38 UTC, shonsirsha commented
This (at least) can be re-used for wallet connect qr code scanning. 🙂

2023-08-21 14:41 UTC, thisconnect requested changes
nice test !

2023-08-22 11:17 UTC, shonsirsha commented on frontends/web/src/hooks/use-qr-code-reader.ts
> +            setHasCamera(videoInputDevices.length > 0);
good point - always nice to be safe. Changes made & rebased. PTAL 🙏

2023-08-22 11:24 UTC, shonsirsha commented
Renamed the hook and test file to `qrcodescanner` & `qrcodescanner.test` respectively to keep consistency between hook files naming.

2023-08-22 11:38 UTC, thisconnect approved these changes
LGTM 👍

2023-08-22 12:19 UTC, merged