backend: add unit tests for eth address>account code matching
digitalbitbox/bitbox-wallet-app pull request #2254
Opened 2023-09-21 11:59 UTC by Tomasvrba

2023-09-26 08:23 UTC, benma requested changes
thx!

2023-09-26 08:23 UTC, benma commented on backend/coins/eth/account_test.go
> +		assert.Contains(t, err.Error(), "invalidAddress")
can check here that it is actually `errors.ErrInvalidAddress` 

    require.Equal(s.T(), errors.ErrInvalidAddress, errp.Cause(err))

2023-09-27 09:11 UTC, Tomasvrba commented
Not sure why CI failed because of locize, there aren't any changes that should affect that here and running make locize-fix didn't change any files

2023-09-27 09:25 UTC, thisconnect commented
I think we merged a formatting issue and probably due to nodejs not running properly. nodejs should be fixed on master and will be merged into staging-walletconnect

If I run locize fix I get changes, what output did you get, did locize even run?

instead of installing locize globally you can also do `npx locize-cli format frontends/web/src/locales --format json`

> Not sure why CI failed because of locize, there aren't any changes that should affect that here and running make locize-fix didn't change any files

2023-10-02 11:40 UTC, benma commented
@Tomasvrba maybe a rebase will fix it? seems like it is fixed in the staging branch.

2023-10-02 12:33 UTC, Tomasvrba commented
> @Tomasvrba maybe a rebase will fix it? seems like it is fixed in the staging branch.

should be all fixed up now

2023-10-03 08:54 UTC, merged