Show recovery words warning
digitalbitbox/bitbox-wallet-app pull request #2263
Opened 2023-09-27 21:43 UTC by NicolaLS

Show a warning in the app before showing the recovery words (mnemonic) on the device:
_Never share your recovery words with anyone. Your recovery words give full access to your wallet. If someone is asking you for your recovery words, it's a scammer, do not share them!_

Requires: #2262 to be merged

Please point me in the right direction on how to style this, if I understood correctly it should not be part of the `description` in the `app.json` but another key (`warning`) this means it could also use a strong tag anywhere but we would need to use `SimpleMarkup` instead of `Message`.

note: **don't look at the 'files changed' diff as it contains commits from the confrim dialog refactor, select the last commit to see the relevant changes**

2023-09-28 16:36 UTC, NicolaLS commented on frontends/web/src/routes/settings/components/device-settings/show-recovery-words-setting.tsx
> +      <Dialog title={t('backup.showMnemonic.title')} open={showDialog} onClose={() => setShowDialog(false)}>
the `onClose` does not seem necessary but otherwise you can't open the dialogue again after exiting with `esc` key instead of the cancel button.

2023-09-28 17:58 UTC, thisconnect requested changes

2023-09-28 17:58 UTC, thisconnect commented on frontends/web/src/routes/settings/components/device-settings/show-recovery-words-setting.tsx
> +      }
nit: there should be no need for wrapping `<SimpleMarku` in brackets `{`

2023-09-29 06:42 UTC, thisconnect approved these changes
thanks! tested LGTM 👍

2023-09-29 06:43 UTC, merged