frontend: add poster attribute video tag
digitalbitbox/bitbox-wallet-app pull request #2299
Opened 2023-10-13 12:12 UTC by NicolaLS

In the scan-qr-video component, we use a html video tag which has an unappealing placeholder image. Adding a poster attribute changes that placeholder image, we use an empty svg in this case.

2023-10-13 18:56 UTC, NicolaLS commented
this is how it looks without the attribute:
![Screenshot_20231012_203128_BitBoxApp DEBUG](https://github.com/digitalbitbox/bitbox-wallet-app/assets/90551797/12124774-ebc1-49d2-a671-549a8349146a)

and this with the `poster` tag containing an empty svg (the animation of the three dots make it look weird on that screenshot):

![Screenshot_20231012_204944_BitBoxApp DEBUG](https://github.com/digitalbitbox/bitbox-wallet-app/assets/90551797/63726194-e717-4abd-a7dc-7ea6792f3a53)

2023-10-16 12:45 UTC, thisconnect requested changes

2023-10-16 12:45 UTC, thisconnect commented on frontends/web/src/routes/account/send/components/inputs/scan-qr-video.tsx
> +        poster="%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%2264%22%20height=%2248%22%3E%3C/svg%3E'"
Please remove the singlequote at the end.

2023-10-16 15:13 UTC, thisconnect approved these changes
untested LGTM 👍

2023-10-17 09:43 UTC, Beerosagos approved these changes
tACK on android and qt-linux! :+1:

2023-10-17 10:01 UTC, merged