Watchonly: prompt user to connect device/keystore when needed
digitalbitbox/bitbox-wallet-app pull request #2347
Opened 2023-11-09 08:32 UTC by benma

Whenever the keystore is needed to perform an action on an account (verify address, send tx, ...), the user is prompted to connect the device/keystore. 

- If it is already connected, it proceeds automatically.
- If the user cancels, whatever action the user is doing aborts
- If the user connects the wrong device (or right device but wrong passphrase), the action aborts with a relevant error message

This is invoked automatically in the backend whenever the keystore is needed. In addition, an API call `connectKeystore()` is added that manually invokes this prompt. This is useful to prompt the user to connect before upfront, e.g. in the first step of the "Buy crypto" workflow instead of in the middle of it.

2023-11-09 08:48 UTC, benma commented on frontends/web/src/routes/account/receive/receive.tsx
> +                        setVerifying(false);
This is delayed by 300ms because the Dialog component has this timeout before calling onClose. Seems like a bug. @thisconnect

2023-11-09 16:16 UTC, Beerosagos requested changes
Very nice! Just a small change is required in info.tsx + a few nits

2023-11-13 09:15 UTC, benma commented on appveyor.yml
> +# See https://www.appveyor.com/docs/windows-images-software/#golang
fixed

2023-11-13 09:15 UTC, benma commented on backend/connectkeystore.go
> +func (c *connectKeystore) onConnect(keystore keystore.Keystore) {
added

2023-11-13 09:15 UTC, benma commented on backend/connectkeystore.go
> +func (c *connectKeystore) cancel(cause error) {
added

2023-11-13 09:15 UTC, benma commented on frontends/web/src/hooks/api.ts
> +export const useSubscribeReset = <T>(
fixed

2023-11-13 09:15 UTC, benma commented on frontends/web/src/routes/buy/info.tsx
> +  const handleProceed = async () => {
fixed

2023-11-13 15:16 UTC, Beerosagos approved these changes
partially tested ACK (didn't test the last changes, but code looks good)

2023-11-13 16:03 UTC, merged