frontend: created a toggle for watch-only for each account
digitalbitbox/bitbox-wallet-app pull request #2374
Opened 2023-11-28 11:25 UTC by shonsirsha

this toggle is placed inside the 'Edit' dialog in the manage accounts page. The toggle won't be shown if the user disables watch-only in the settings/appearance page.

Preview (when watchonly is disabled from settings/appearance page) - stays the same:
<img width="776" alt="xas" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/fe1bfc4f-8b4b-44aa-9f5e-8103626fe741">

Preview (when watchonly is enabled from settings/appearance page):

https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/366dd608-e45a-4ea7-8de4-5ea215b555de

Preview (when BB02 is unplugged and watchonly is enabled from settings/appearance page):

https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/0a327a0a-f8eb-4d63-979b-b7272c2ccda5

2023-11-28 14:49 UTC, thisconnect requested changes
I think I found a bug, but that was probably already there. I only tested this branch commit fa794c6cc3ad7fff3474ec67111d7bb01e0a8d90

2023-11-28 14:49 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +            event.target.disabled = true;
during testing I could not really see that this disabled the toggle.

2023-11-28 14:49 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +                      })
I tested with a 2nd wallet and got into a situation when it showed 2 dialogs 🤔  

![Screen Shot 2023-11-28 at 15 37 37](https://github.com/digitalbitbox/bitbox-wallet-app/assets/546900/c97875d3-c63f-4fe2-aeae-a1740373d6eb)

2023-11-28 14:49 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +                      })
Looks like the reason is that I have 2 items in `accountsByKeystore` and Dialog open condition is just if `editAccountCode` is truthy. This is the reason it opens a dialog for every keystore.

2023-11-28 17:45 UTC, thisconnect approved these changes
nice LGTM with suggestion

2023-11-28 17:45 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +                        {watchonly &&
is the fragment needed here or would that work?

```suggestion
                        {watchonly && this.renderWatchOnlyToggle()}
```

2023-11-29 04:27 UTC, benma commented
I haven't tested this PR, but in the video, it does not actually show the account disappearing, which would happen if you clicked that button on an account while in watch-only (bitbox02/keystore not connected). what happens to the dialog in that case?

No strong opinion, but should the prompt not be **before** performing the action of hiding the account, in case the user did not actually want the account to disappear immediately? (that was why I suggested a prompt initially)

2023-11-29 09:34 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +                  {currentlyEditedAccount && (
just one more question: if the Dialog is conditionally rendered it wont animate on small screen correct?

2023-11-29 10:30 UTC, thisconnect commented
LGTM

2023-11-29 10:45 UTC, merged