frontends: move frontends/android/goserver go backend/mobileserver
digitalbitbox/bitbox-wallet-app pull request #2454
Opened 2023-12-21 14:34 UTC by benma

An iOS app in frontends/ios would use the same package, just with a different build target.

2023-12-21 16:33 UTC, Beerosagos requested changes
App building works, but looks like there is still some `goserver` somewhere and the mobileserver.aar is not correctly ignored by git. After building my git status is:

```
beerosagos@kiddo:~/shift/repo/beero/bitbox-wallet-app$ git status
On branch pr/2454
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   frontends/android/BitBoxApp/mobileserver/mobileserver.aar

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	frontends/android/BitBoxApp/goserver/
	frontends/android/goserver/

no changes added to commit (use "git add" and/or "git commit -a")
```

Also, I'm wondering if it would make sense to move mobileserver outside the frontends folder, one level up (if that's possible). No strong opinion though

2023-12-21 16:33 UTC, Beerosagos commented on Makefile
> +	cd frontendS/mobileserver && $(MAKE) clean
typo: frontendS

2023-12-22 22:44 UTC, benma commented on Makefile
> +	cd frontendS/mobileserver && $(MAKE) clean
fixed

2023-12-22 22:46 UTC, benma commented
> App building works, but looks like there is still some `goserver` somewhere and the mobileserver.aar is not correctly ignored by git. After building my git status is:
> 
> ```
> beerosagos@kiddo:~/shift/repo/beero/bitbox-wallet-app$ git status
> On branch pr/2454
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   frontends/android/BitBoxApp/mobileserver/mobileserver.aar
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	frontends/android/BitBoxApp/goserver/
> 	frontends/android/goserver/
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> ```
> 

It is actually in .gitignore, but I also committed it by accident, so it was tracked. I removed it from the commit now.

> Also, I'm wondering if it would make sense to move mobileserver outside the frontends folder, one level up (if that's possible). No strong opinion though

Can do, or maybe to backend/mobileserver (bridgecommon is also in backend/bridgecommon)? Let me know what you like best, I am okay with any location.

2024-01-03 09:26 UTC, Beerosagos commented
> Can do, or maybe to backend/mobileserver (bridgecommon is also in backend/bridgecommon)? Let me know what you like best, I am okay with any location.

backend/mobileserver looks good! :+1:

2024-01-03 22:21 UTC, benma commented
> > Can do, or maybe to backend/mobileserver (bridgecommon is also in backend/bridgecommon)? Let me know what you like best, I am okay with any location.
> 
> backend/mobileserver looks good! 👍

Moved there!

2024-01-04 08:04 UTC, Beerosagos approved these changes
tACK!

2024-01-04 08:29 UTC, merged