frontend: fix actions btns spacing when collapsed
digitalbitbox/bitbox-wallet-app pull request #2473
Opened 2024-01-01 02:10 UTC by shonsirsha

Before:
<img width="1483" alt="2e" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/41bf1bcc-a3e7-430c-8756-927e74ce323e">

After:
<img width="1483" alt="ewda" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/d78634f2-9194-4854-9182-0c84fdfd1047">

<img width="948" alt="asdsa" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/ada56f30-31eb-46f1-9d80-25f3c9bd1b21">

2024-01-02 18:44 UTC, thisconnect requested changes
I fount a tiny somewhat related bug:

it seems that the WalletConnect button text disappears but the icon is not centered.

![Screen Shot 2024-01-02 at 19 41 37](https://github.com/digitalbitbox/bitbox-wallet-app/assets/546900/1ada6ff7-e290-425e-aa88-94dab7203d17)

Since you are here could you look into that as well?

2024-01-03 04:36 UTC, shonsirsha commented on frontends/web/src/routes/account/account.module.css
> +        width: 91%;
hehe, wouldn't know either. My best bet would be due to eyeballing the size of the buttons. But 100% looks fine as well. I'll remove the max-width too as that seems to be not useful as well as the `flex` shorthand property.

2024-01-03 04:39 UTC, shonsirsha commented
PTAL @thisconnect , fixed the bug you found by always the centreing the items in the button.

2024-01-03 12:51 UTC, thisconnect approved these changes
tested LGTM

2024-01-03 13:50 UTC, merged