experiment] frontend: show spinner after unlock, before accounts are loaded
digitalbitbox/bitbox-wallet-app pull request #2544
Opened 2024-02-07 15:40 UTC by benma

After unlock, especially the first time, it can take many seconds for the initial set of accounts to be loaded. Until then, the app shows nothing in the sidebar and 'Please connect your device to get started'.

The user is easily confused, it seems as something went wrong.

We can probably speed up this loading with firmware and app changes, but this is a quick improvement that shows a spinner until the accounts become available.

2024-02-07 15:45 UTC, thisconnect requested changes
nice 2 small nits

2024-02-07 15:45 UTC, thisconnect commented on frontends/web/src/hooks/backend.ts
> +}
rename to `hooks/keystores`?

2024-02-07 15:45 UTC, thisconnect commented on frontends/web/src/routes/device/waiting.tsx
> +  console.log('LOL', keystores, devices);
console.log

2024-02-07 15:58 UTC, benma commented on frontends/web/src/routes/device/waiting.tsx
> +  const devices = useSync(getDeviceList, syncDeviceList);
i was hoping only the keystore check would be enough but somehow the frontend gets the keystore event way too late (looks like the backend/frontend is overloaded with work or handling events during that time, and we have no way to prioritize certain events at the moment), so i added the devices check too, which necessarily comes earlier (already before the unlock). software keystore

2024-02-21 13:35 UTC, Beerosagos reviewed
It is a nice improvement, but the fact that the loading screen disappears after loading the first accounts, but other accounts can still be discovered and added to the sidebar looks a bit buggy to me.
Would it be possible to fire an event when the account discovery stops looking for new accounts and use that to hide the loading screen?

2024-02-22 09:18 UTC, thisconnect commented
> the fact that the loading screen disappears after loading the first accounts, but other accounts can still be discovered and added to the sidebar looks a bit buggy to me.

Generally I think it is better to show and render all data that is available, and if 1 account is already found, list it incrementally. I think it's better than having a loading screen for seconds/minutes and nothing happens.

@Beerosagos what if there was a small loading icon so that it is clear that it is still searching? (but also that would need some kind of discovery-is-finished event)

2024-02-22 09:23 UTC, Beerosagos commented
> @Beerosagos what if there was a small loading icon so that it is clear that it is still searching? (but also that would need some kind of discovery-is-finished event)

That would be really nice, imo

2024-04-22 15:29 UTC, benma commented
Closing in favor of https://github.com/digitalbitbox/bitbox-wallet-app/pull/2683

2024-04-22 15:29 UTC, closed without merging