Intermediate update
digitalbitbox/bitbox-wallet-app pull request #2637
Opened 2024-03-18 11:51 UTC by benma

2024-03-19 15:04 UTC, Beerosagos requested changes

2024-03-19 15:04 UTC, Beerosagos commented on backend/devices/bitbox02bootloader/assets/firmware-btc.v9.15.0.signed.bin.sha256
Also, the firmware binaries for v9.16 should be deleted in the last commit, right?

2024-03-20 16:54 UTC, benma commented on backend/devices/bitbox02bootloader/firmware.go
> +			monotonicVersion: 38,
Why? The binary has to be like this because the binary is embedded.

2024-03-20 16:55 UTC, benma commented on backend/devices/bitbox02bootloader/firmware_test.go
> +			fwVersion := binary.LittleEndian.Uint32(fwBinary[392:396])
It is a unit test, if it panics the test will fail :) an explicit check would only lead to a nicer error formatting in the unit test.

2024-03-20 16:56 UTC, benma commented on backend/devices/bitbox02bootloader/firmware_test.go
> +		fwInfo, err = nextFirmware(product, 36)
hmm I think I disagree, as this intermediate version is set in stone and will never change. Making the test generic would nearly replicate the logic of the original function, not adding much value.

2024-03-21 08:23 UTC, Beerosagos commented on backend/devices/bitbox02bootloader/firmware.go
> +			monotonicVersion: 38,
oh, right!

2024-03-21 08:27 UTC, Beerosagos commented on backend/devices/bitbox02bootloader/firmware.go
> +			monotonicVersion: 38,
What I meant is that 'firmwareVersionMulti' and `firmwareVersionBTCOnly` are in dedicated variables, while monotonic version is not. Would be nice to have everything in the same place, to make future updates in the same piece of code. But again, just a personal opinion and a nit.

2024-03-26 11:10 UTC, Beerosagos approved these changes
partially tested ACK

2024-04-02 11:40 UTC, merged