frontend/settings: add 'Export logs' feature
digitalbitbox/bitbox-wallet-app pull request #2640
Opened 2024-03-18 15:36 UTC by strmci

This commit introduces a new feature to the Settings section, enabling users to easily export log files for troubleshooting purposes. With this addition, users can access log files without the need to navigate through the application's files manually, simplifying the process of sharing logs with support team.

When 'Export Logs' is selected from the Settings menu, the save dialog opens, allowing the user to specify the destination folder. Upon confirmation, the log file, including the current date and time in the filename, is then copied to the selected folder.

2024-04-10 15:03 UTC, Beerosagos requested changes

2024-04-10 15:03 UTC, Beerosagos commented on frontends/web/src/locales/en/app.json
> +        "description": "Export log file to help with trouble shooting and support.",
typo: troubleshooting

2024-04-10 15:55 UTC, Beerosagos commented
One more thing: please mention in the commit message that the export feature is only available on Qt :)

2024-04-10 19:46 UTC, benma commented on frontends/web/src/routes/settings/components/advanced-settings/export-log-setting.tsx
> +    .then(result => {
also lowercase `logs()`?

2024-04-15 14:08 UTC, strmci commented on frontends/web/src/routes/settings/components/advanced-settings/export-log-setting.tsx
> +  const csvExportDisabled = runningInAndroid();
Removed the unnecessary `csvExportDisabled` constant and adjusted the condition to display the Export logs feature by adding `debug === true`.

2024-04-15 14:09 UTC, strmci commented on frontends/web/src/routes/settings/components/advanced-settings/export-log-setting.tsx
> +    .then(result => {
Updated to `await` and lowercase `logs()`.

2024-04-15 14:11 UTC, strmci commented on backend/handlers/handlers.go
> +func (handlers *Handlers) exportLog(r *http.Request) (interface{}, error) {
Renamed to `postExportLog` and created a dedicated backend function `ExportLogs`

2024-04-15 14:13 UTC, strmci commented on frontends/web/src/api/backend.ts
> +  path: string;
Updated to `iSuccess`

2024-04-15 14:13 UTC, strmci commented on frontends/web/src/locales/en/app.json
> +        "description": "Export log file to help with trouble shooting and support.",
thanks, fixed

2024-04-15 14:14 UTC, strmci commented
@Beerosagos thanks, I also updated the commit message and PR description.
PTAL

2024-04-17 09:19 UTC, Beerosagos commented
Thanks! One last thing: please add a line in the CHANGELOG about the export logs feature

2024-04-17 12:09 UTC, strmci commented
@Beerosagos CHANGELOG updated

2024-04-17 13:14 UTC, Beerosagos approved these changes
tACK! nice :+1:

2024-04-17 13:42 UTC, merged